In [3]:
import numpy as np
#1) Create Two numpy array of size 3 X 2 and 2 X 3
#2) Randomly Initalize that array
a = np.array([[1, 2, 5], [3, 4, 8]])
b = np.array([[7, 3], [2, 8], [5,1]])
print(a)
print()
print(b)

[[1 2 5]
 [3 4 8]]

[[7 3]
 [2 8]
 [5 1]]


In [4]:
#3) Perform matrix multiplication
x = np.dot(b, a)
y = np.dot(a, b)
print(x)
print()
print(y)

[[16 26 59]
 [26 36 74]
 [ 8 14 33]]

[[36 24]
 [69 49]]


In [5]:
#4) Perform elementwise matrix multiplication
#it will produce error as parameters are not of same size
p=a*b
q=b*a
print(p)
print()
print(q)

ValueError: ignored

In [6]:
#but we can perform multiplication of them with another matrix of same size or scalers
p = np.array([[1,1,2],[2,2,6]])
print(p*a)
print()
print(5*b)

[[ 1  2 10]
 [ 6  8 48]]

[[35 15]
 [10 40]
 [25  5]]


In [8]:
#5) Find mean of first matrix
mean = np.mean(b)
meanByCols = np.mean(b, axis=0)
meanByRows = np.mean(b, axis=1)
print('mean',mean)
print()
print('meanByCols',meanByCols)
print()
print('meanByRows',meanByRows)

mean 4.333333333333333

meanByCols [4.66666667 4.        ]

meanByRows [5. 5. 3.]


In [15]:
#6) Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version
import pandas as pd
a=pd.read_csv('/content/mtcars.csv')
print(a)
a['mpg'] = a['mpg'] - np.mean(a['mpg'], axis=0)
a['cyl'] = a['cyl'] - np.mean(a['cyl'], axis=0)
a['disp'] = a['disp'] - np.mean(a['disp'], axis=0)
a['hp'] = a['hp'] - np.mean(a['hp'], axis=0)
a['drat'] = a['drat'] - np.mean(a['drat'], axis=0)
a['wt'] = a['wt'] - np.mean(a['wt'], axis=0)
a['qsec'] = a['qsec'] - np.mean(a['qsec'], axis=0)
a['vs'] = a['vs'] - np.mean(a['vs'], axis=0)
a['am'] = a['am'] - np.mean(a['am'], axis=0)
a['gear'] = a['gear'] - np.mean(a['gear'], axis=0)
a['carb'] = a['carb'] - np.mean(a['carb'], axis=0)
print()
print(a)

                  model   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2            Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  ...  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  ...  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  ...  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  ...  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  ...  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  ...  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  ... 